### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gmaclennan** [digidem/react-dimensions#1]
For any continued discussion on https://github.com/facebook/fixed-data-table/issues/62

**Comment by jdelafon** [comment]
So I gave it another try, but still don't get it right.
Say I have a React component MyTable

```
var MyTable = React.createClass({....
     render: .....
          return <Table
              width={this.props.tableWidth}
              height={this.props.tableHeight}
          ></Table>;
```

Now when I want to include it into another component (inside the same file, so no export), I'd do a

```
var OuterComponent = React.createClass({...    
    render:....
        return <div id='container'><Mytable /></div>
```

So if I want to add dimensions, I do instead

```
var Dimensions = require('react-dimensions');

var OuterComponent = React.createClass({...   
    render:....
        var MyResponsiveTable = Dimensions()(MyTable);
        return <div id='container'><MyResponsiveTable /></div>
```

because I expect MyResponsiveTable to be a react component similar to MyTable, but with additional internal props. But all I see rendered is a '0'.

**Comment by gmaclennan** [comment]
`var MyResposiveTable = ...` should not be inside your render method, it should be just before `var OuterComponent …`

As it is you are creating a new instance of the component every time you render - essentially you're putting a `React.createClass = …` inside the render method.

**Comment by jdelafon** [comment]
Right. The following renders a div with 100% width and height, but containing only '0'. If I replace `<MyResponsiveTable />` by `<MyTable />`  it is displayed correctly.

```
var MyTable = React.createClass({
          ....
});
var MyResponsiveTable = Dimensions()(MyTable);

var OuterComponent = React.createClass({...   
    render:....
        return <div id='container'><MyResponsiveTable /></div>
```

Rendered HTML:

```
<div id="container" data-reactid=".0.2.0.1">
<div style="width:100%;height:100%;padding:0;border:0;" data-reactid=".0.2.0.1.0">0</div>
</div>
```

**Comment by gmaclennan** [comment]
Spotted another error in your code: `this.props.tableWidth` should be `this.props.containerWidth`. The console should give you feedback about these errors.

**Comment by jdelafon** [comment]
My bad, it almost works now ! Actually the '0' div is only the first render, and when I resize the window my table appears and takes the whole width.
What did I do wrong so that the `containerWidth` prop is `undefined` on first render ? 
Also it does not work for the height - but neither did with my previous version. Should I set explicitly the height of every parent container in the dom to 100% for it to work ?

If I manage to make it work I'll submit a PR with documentation for dummies.

**Comment by gmaclennan** [comment]
Thanks @muraveill, I'm glad you got it working. You need to set explicit height for 100% to work - this is a CSS issue, a Google search should turn up some explanations. I'm not sure why containerWidth is undefined on first render, it may be because the DOM element does not have a width set? No time right now to investigate, but I'll look into it at some point.

**Comment by jdelafon** [comment]
If that can help, in my current working version (without the react-dimensions module), the containerWidth state is set only if `this.isMounted()`, and the resize event listener is attached to `componentDidMount`. Also it is actually triggered once in `componentDidMount` to ensure the resize on first load. Having an empty render on first load looks like your resize callback is called before the component gets mounted.

Is there a way to trigger a resize event of the component wrapped by "Dimensions", inside its `componentDidMount` ?

**Comment by gmaclennan** [comment]
Currently `containerWidth` and `containerHeight` are only set on `componentDidMount`, and the resize event is attached: https://github.com/digidem/react-dimensions/blob/master/index.jsx#L76-L79

It was working for me. If you have something that is not working, paste it here.

**Comment by jdelafon** [comment]
I think I get it : from your source code,

```
<div style={style} ref='container'>
        {this.state.containerHeight && <ComposedComponent {...this.state} {...this.props}/>}
</div>
```

That is, if this.state.containerHeight is not defined, the content of the div will be '0'. I gave a fixed height to my table because the container div has no height defined (which I intended to solve later on). Since children components are rendered before the parents, the container height is still undefined on first render.
IMHO width and height should remain independent.

**Comment by gmaclennan** [comment]
Hopefully the docs are a little clearer now, the issue on height not being set is fixed, and the example should help.

**Comment by jdelafon** [comment]
It is clear now, and works like a charm. Thanks !

**Comment by jdelafon** [comment]
Any chance that the 0.0.4 version for react 0.13 could fix the issue of height not being set as well, please ? Now react 0.14 together with fixed-data-table does not work for me, and react-dimensions 1.0.0 requires react 0.14.

**Comment by gmaclennan** [comment]
done in v0.1.1

**Comment by devnacho** [comment]
\+ 1 to fix the height issue on the 0.0.4 version.

Please!

Thanks!!

**Comment by jdelafon** [comment]
It works, thanks a lot.

**Comment by steakchaser** [comment]
@muraveill how were you able to solve the problem where the table does not show on first render, but then does appear after you resize?  I've set an explicit height (via style) on the parent div and table itself.  Using `1.0.2` with `0.14.2`.  Thanks!

**Comment by jdelafon** [comment]
@steakchaser I could not solve it and use fixed height. But at least I understood why and it is not because of react-dimensions.

I guess that like me you are using bootstrap grids: bootstrap columns have no height, whatever "height: 100%" you try everywhere in your css (I tried adding that on every single div), so when the component is rendered it uses the height of the parent that is 0. 
In my particular case, I am using react-dimensions with fixed-data-table: when the component updates (on resize event), the bs column has the height of the table header, so the table gets one more row, and it grows like that as one continues to resize the component... Ugly.

Actually there are css solutions but I lost patience struggling with it:
- display: table / table-row / table cell together with float: none on bootstrap grid elements
- not tried: http://www.minimit.com/articles/solutions-tutorials/bootstrap-3-responsive-columns-of-same-height

@gmaclennan A nice feature would be the ability to choose what element one wants to get the height from ! Not only that would solve the problem (and many use bootstrap), but also one could do funky things.

**Comment by steakchaser** [comment]
@muraveill thanks!  fixed height for the actual `Table` component via `height={800}` works for me and is good enough for now.  I'm not sure why I didn't understand this from the README or this thread, but thanks!

**Comment by craigcosmo** [comment]
@jdelafon base on the discussion, I assume you got it to work. If you don't mind, please have a look at my issue https://github.com/digidem/react-dimensions/issues/37

**Comment by DLTKAbelLeal** [comment]
Is anyone has a typescript definition for react-dimensions? I'm trying to create one but still having some issues in the code. My table needs to be responsive when both side panels are expanded. I have toggleable panels in both sides of the table and I'm having hard time to make the table responsive. I'm using react fixed-data-table in typescript ES6.
