### ISSUE TITLE
className option is in docs, but doesn't seem to be in npm

### ISSUE THREAD

**Issue by jharris4** [digidem/react-dimensions#33]
I'd like to use the className option you added in a recent version, but despite being in the readme, it isn't yet available in 1.2.0 on npm.

Are you planning to release a new version soon?

Thanks

**Comment by mgeduld** [comment]
I too need this! When can we expect an update? Thanks.

**Comment by gmaclennan** [comment]
My apologies, `master` had some breaking changes that I am still experimenting with, measuring the parent `<div>` instead of the wrapper.

I re-based the feature adding `className` on v1.2.0 and published to npm as 1.3.0. This is on the [v1.3.0](https://github.com/digidem/react-dimensions/tree/v1.3.0) branch. `master` will track experimental work on breaking changes.
